language: php

php:
- 7.1
- 7.2

install: composer install --dev --no-interaction

script:
- vendor/bin/phpunit --coverage-clover=coverage.xml
- composer stan

after_success:
- bash <(curl -s https://codecov.io/bash)
